### ISSUE TITLE
Debug doesn't work for me

### ISSUE THREAD

**Issue by PandaWood** [maty21/mocha-sidebar#103]
I can't debug any tests, though I can run them OK.
I just get an error and the breakpoint is not hit.

### Description
I just get this log and error:
```
C:\Program Files\nodejs\node.exe --inspect-brk=42287 ..\..\..\..\Users\me\.vscode\extensions\maty.vscode-mocha-sidebar-0.19.0\node_modules\mocha\bin\_mocha **/*.spec.ts --grep '^App UrlEncoder can encode 1 basic arg with &$' -r ts-node/register --compilers '[object Object]' 
Debugger listening on ws://127.0.0.1:42287/fce66ad9-ee34-4ef1-a8ca-fdd93821d599

Debugger attached.

c:\Users\me\.vscode\extensions\maty.vscode-mocha-sidebar-0.19.0\node_modules\mocha\bin\_mocha:302

  if (mod[0] == '.') mod = join(process.cwd(), mod);

         ^

TypeError: Cannot read property '0' of undefined
 at c:\Users\me\.vscode\extensions\maty.vscode-mocha-sidebar-0.19.0\node_modules\mocha\bin\_mocha:302:10
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (c:\Users\me\.vscode\extensions\maty.vscode-mocha-sidebar-0.19.0\node_modules\mocha\bin\_mocha:297:19)
    at Module._compile (module.js:570:14)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
```

#### Steps to Reproduce
I just add a breakpoint and press the "debug" graphic "Debug Level"

#### Expected Results
I expect it to run and stop on the breakpoint I added

#### Actual Results
See error in description

#### Settings file

```
 "mocha.files.glob": "**/*.spec.ts",
    "mocha.requires": [
        "ts-node/register"
    ],
    "mocha.options": {
        "compilers": {
            "ts": "ts-node/register"
        }
	},
	"mocha.logVerbose": true
``` -->
```
```


### Versions

- VScode: v1.23.1
- Mocha SideBar: v0.19.0 
- Node Version: v8.4


### OS version
<!-- Check all that apply -->
- [ ] Linux 
- [ ] Mac
- [x ] Windows



#### Example for reproducing
I'll do this if the stack trace makes it hard to reproduce

**Comment by maty21** [comment]
It's seems like that you set the compiler I'm object try to remove the object

**Comment by maty21** [comment]
If I understood you correctly the comment in 103 fix it for you

**Comment by PandaWood** [comment]
Thanks @maty21 you are right, removing that the compiler option from the settings prevents the error.
I also realize, I needed to hit "Debug" to go into debug "mode" and then run the test.
But now it works, thank you.

**Comment by maty21** [comment]
Nice if you like the extension we will appreciate if you star us and rate us thanks
