### ISSUE TITLE
How can I pass options to mocha?

### ISSUE THREAD

**Issue by spacem** [maty21/mocha-sidebar#12]
Hi,
I have a codebase in typescript so usually I am running mocha with the parameter --compilers ts:ts-node/register

I saw you have a mocha.options parameter in this extension but and I tried a few things but cant get it to work. 
  "mocha.options": {
    "compilers": {
      "ts": "ts-node/register"
    }
  },
^ not working

Are these types of options supported?

**Comment by maty21** [comment]
should be supported i will debug it

**Comment by maty21** [comment]
require support should be added to the configuration option

**Comment by Talv** [comment]
Is it possible to pass options from `mocha.opts` file? In cli there is `--opts` parameter (`mocha --opts mocha.opts`). Can I do the same with this extension?

I've tried following config, but doesn't seem to work as I get the error message saying it failed to parse `*.ts` files.
```json
{
    "mocha.options": {
        "opts": "mocha.opts"
    },
    "mocha.files.glob": "tests/**/*.ts"
}
```

My `mocha.opts`:
```
--require mocha.env.js 
--require ts-node/register 
--require source-map-support/register
--recursive
--watch-extensions tsx,ts 
--timeout 0
tests/**/*.ts
```

**Comment by Talv** [comment]
I skipped `mocha.opts` for now, and used this config:
```json
{
    "mocha.options": {
    },
    "mocha.requires": ["ts-node/register"],
    "mocha.files.glob": "tests/**/*.ts"
}
```

Which gives me:
```
Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:513:15)
    at Function.Module._load (module.js:463:25)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.register (/run/media/kk/nt1/ntdev/plaxtony/node_modules/ts-node/src/index.ts:188:25)
    at Object.<anonymous> (/run/media/kk/nt1/ntdev/plaxtony/node_modules/ts-node/register.js:1:15)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/kk/.vscode/extensions/maty.vscode-mocha-sidebar-0.8.9/worker/findtests.js:13:3)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
```

Can this extension work with TypeScript? If so, what's the proper way to configure it.

**Comment by maty21** [comment]
should be fixed for version  0.9.0 use this configuration
```
 "mocha.options": {
        "compilers": {
            "ts": "ts-node/register"
        }
    },
    "mocha.requires": [
        "ts-node/register"
    ],
```
if it dosent work for you try to install typescript locally in your package(npm i typescript) not globally maybe as dev dependency
 
thats works for me let me know if it fix your issues 

thanks :)

**Comment by spacem** [comment]
Thanks for the fast turnaround - seems to work well!

**Comment by maty21** [comment]
np :) 

btw find related issue in ionic with typescript [https://github.com/ionic-team/ionic-app-scripts/issues/542](https://github.com/ionic-team/ionic-app-scripts/issues/542)

**Comment by ehartford** [comment]
I followed this guide, but still debugging doesn't work.  How can I enable source-map?
