### ISSUE TITLE
Cannot run tests from sidebar. TypeScript

### ISSUE THREAD

**Issue by mtuchkov** [maty21/mocha-sidebar#121]
### Description
Fails with mocha_1.describe is not a function if I explicitly import the methods describe nad it

#### Steps to Reproduce
import { describe, it } from 'mocha';

describe('tests', async () => {
    it('test3', async () => {
        console.log('asdsad')
    });
});

#### Expected Results
test pass

#### Actual Results

TypeError: mocha_1.describe is not a function
    at Object.<anonymous> (/Users/mtuchkov/GitHub/saas/specs/test.spec.ts:3:1)
    at Module._compile (module.js:635:30)
    at Module.m._compile (/Users/mtuchkov/GitHub/saas/node_modules/ts-node/src/index.ts:400:23)
    at Module._extensions..js (module.js:646:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/mtuchkov/GitHub/saas/node_modules/ts-node/src/index.ts:403:12)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at /Users/mtuchkov/.vscode/extensions/maty.vscode-mocha-sidebar-0.20.12/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/mtuchkov/.vscode/extensions/maty.vscode-mocha-sidebar-0.20.12/node_modules/mocha/lib/mocha.js:217:14)
    at Glob (/Users/mtuchkov/.vscode/extensions/maty.vscode-mocha-sidebar-0.20.12/worker/findtests.js:74:15)
    at f (/Users/mtuchkov/.vscode/extensions/maty.vscode-mocha-sidebar-0.20.12/node_modules/once/once.js:25:25)
    at Glob.<anonymous> (/Users/mtuchkov/.vscode/extensions/maty.vscode-mocha-sidebar-0.20.12/node_modules/glob/glob.js:151:7)
    at emitOne (events.js:116:13)
    at Glob.emit (events.js:211:7)
    at Glob._finish (/Users/mtuchkov/.vscode/extensions/maty.vscode-mocha-sidebar-0.20.12/node_modules/glob/glob.js:197:8)
    at done (/Users/mtuchkov/.vscode/extensions/maty.vscode-mocha-sidebar-0.20.12/node_modules/glob/glob.js:182:14)
    at Glob._processGlobStar2 (/Users/mtuchkov/.vscode/extensions/maty.vscode-mocha-sidebar-0.20.12/node_modules/glob/glob.js:637:12)
    at /Users/mtuchkov/.vscode/extensions/maty.vscode-mocha-sidebar-0.20.12/node_modules/glob/glob.js:626:10
    at RES (/Users/mtuchkov/.vscode/extensions/maty.vscode-mocha-sidebar-0.20.12/node_modules/inflight/inflight.js:31:16)
    at f (/Users/mtuchkov/.vscode/extensions/maty.vscode-mocha-sidebar-0.20.12/node_modules/once/once.js:25:25)
    at lstatcb_ (/Users/mtuchkov/.vscode/extensions/maty.vscode-mocha-sidebar-0.20.12/node_modules/glob/glob.js:519:7)
    at RES (/Users/mtuchkov/.vscode/extensions/maty.vscode-mocha-sidebar-0.20.12/node_modules/inflight/inflight.js:31:16)
    at f (/Users/mtuchkov/.vscode/extensions/maty.vscode-mocha-sidebar-0.20.12/node_modules/once/once.js:25:25)
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at createMocha (/Users/mtuchkov/.vscode/extensions/maty.vscode-mocha-sidebar-0.20.12/worker/findtests.js:66:10)
    at Object.<anonymous> (/Users/mtuchkov/.vscode/extensions/maty.vscode-mocha-sidebar-0.20.12/worker/findtests.js:24:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

#### Settings file

```
"mocha.files.glob": "./specs/**/*.ts",
    "mocha.requires": ["ts-node/register"],
    "mocha.options": {
        "compilers": {
            "ts": "ts-node/register"
        }
    }
```

### Versions

- VScode: v1.24.1
- Mocha SideBar: v0.20.12
- Node Version: v8.9.1

### OS version
- [ ] Linux 
- [x] Mac
- [ ] Windows

**Comment by rwatts3** [comment]
I second this, in fact I have never been able to get typescript tests to work. 

Specifically when I'm using files like 

*.spec.ts, it seems that this doesn't work when there is a second name in the file extension.

**Comment by maty21** [comment]
I'll try to figure out what is the problem probably bad configuration

**Comment by rwatts3** [comment]
Configuration was copied directly from the readme docs.
The only change was the glob pattern, which it runs fine when running mocha directly

**Comment by maty21** [comment]
Yea understood . I think that I have to correct the readme according to the
correct one,but we only tunnling the configuration to mocha so we probably
need to understand how to send it correctly

**Comment by rwatts3** [comment]
Actually i'm not sure if this error helps but this is what i'm seeing in the console.

```sh
ERR Cannot read property 'passed' of undefined: TypeError: Cannot read property 'passed' of undefined
```

**Comment by eramitmittal** [comment]
I am not sure what the actual issue is but my setup with typescript works. Few points:
1. in tsconfig.json compileroptions:module is set as commonjs
2. in tests I am not explicitly importing (really can't see why this should be a problem) describe. Instead I do import 'mocha';
3. mocha is part of node_modules (i.e. it is devDependency in package.json)

**Comment by maty21** [comment]
hi guys 

I updated mocha to the latest stable version ``5.2.0`` should be available for ``0.12.14``
test it and it  seems to be working now with this configuration
```js
  "mocha.requires": [
        "ts-node/register"
    ]
``` 
I also added test inside mocha sidebar under test folder so you should clone and try it if you want 

if you still have the problem with running ts I will be happy to hear

**Comment by cenan** [comment]
I have the exact same problem using mocha `5.2.0`.
VS Code 1.30.0
Mocha SideBar: v0.20.22
Same error, same output.

I have

    "mocha.requires": [
        "ts-node/register"
    ]

in options. `ts-node` version is `7.0.1`

**Comment by maty21** [comment]
Hi @cenan please check issue #157 maybe the settings there  will fix it for you

**Comment by cenan** [comment]
@maty21 I have fixed my issue by removing

    import { describe, it } from 'mocha';

from the first line.

Thank you for this great little extension.

**Comment by maty21** [comment]
Thanks man I should add it to the FAQ
