### ISSUE TITLE
Error when launching VSCode

### ISSUE THREAD

**Issue by mikeerickson** [maty21/mocha-sidebar#169]
I am experiencing the same issue, I am running node 11.6 -- same report as #129  

Just installed this extension, wanted to formulate my own opinion despite many of the negative reviews. So, after installing and selecting the icon on the sidebar, I am greeted with the following error
Failed to run Mocha due to error message: " Cannot read property 'width' of undefined " error trace can be found in the output channel . for more help:
Note: After installation, I quit VSCode and relaunched instead of using reload so I am "clean" per se
There is much more in the output (which shows stack trace) and I can send that over if you wish but didn't want to pollute this forum with that information. If you would like, I can email it to you for your review.

**Comment by mikeerickson** [comment]
Seeing as you might want to review output, I figured it may be helpful now

```
____________________________________________________________________________
trying to searching for tests using these settings: 

    mocha path: mocha
    test files location: test/**/*.js
    files to ignore: **/.git/**/*,**/node_modules/**/*
    environmets: {}
    requires: []
    options:  {}


if you find anything wrong please change those default settings
____________________________________________________________________________
TypeError: Cannot read property 'width' of undefined
    at classLabel (/Users/mikee/Documents/code/oss/messenger/test/testUtils.js:21:51)
    at Object.<anonymous> (/Users/mikee/Documents/code/oss/messenger/test/logger.spec.js:26:10)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at /Users/mikee/.vscode/extensions/maty.vscode-mocha-sidebar-0.20.22/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/mikee/.vscode/extensions/maty.vscode-mocha-sidebar-0.20.22/node_modules/mocha/lib/mocha.js:247:14)
    at Glob (/Users/mikee/.vscode/extensions/maty.vscode-mocha-sidebar-0.20.22/worker/findtests.js:84:15)
    at f (/Users/mikee/.vscode/extensions/maty.vscode-mocha-sidebar-0.20.22/node_modules/once/once.js:25:25)
    at Glob.<anonymous> (/Users/mikee/.vscode/extensions/maty.vscode-mocha-sidebar-0.20.22/node_modules/glob/glob.js:151:7)
    at Glob.emit (events.js:188:13)
```
