### ISSUE TITLE
Does not really work out of the box

### ISSUE THREAD

**Issue by nicck** [maty21/mocha-sidebar#21]
On attempt to run any test command it says "Failed to run tests due to unknown error". Also I can find "undefined" message in Output pane. How can I debug this? "unknown error" is not really informative. Can I see backtrace somewhere so I can guess what is wrong?
(OSX, node8.9, mocha installed into ./node_modules and not globally).

**Comment by nicck** [comment]
Actually when I save file something interesting appears in output:

```
Running Mocha with Node.js at /usr/local/bin/node

Applying Mocha options:
  {
    "recursive": true
  }

Test file(s):


  0 passing (0ms)

###end
------------------------------------
finish failuare amount:0
------------------------------------
```

Usually I run my tests via `yarn test` or `npm test` which invoke following command: `mocha -r dotenv/config --recursive ./test dotenv_config_path=.env.test`. I've added some options to workspace settings:

```
    "mocha.options": {
        "recursive": true
    },
    "mocha.requires": ["dotenv/config"]
```

not sure how can I pass `dotenv_config_path=.env.test` to mocha.

**Comment by maty21** [comment]
Do you have some sample code that I can test and debug it for you tks

**Comment by maty21** [comment]
@nicck  does your tests running from mocha command line?

**Comment by nicck** [comment]
I've created a small repo to show the problem: https://github.com/nicck/mocha-sidebar-test-app

```
~/Code/testapp master
❯ yarn     
yarn install v0.27.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 0.83s.
                                                                                                                        
~/Code/testapp master
❯ yarn test
yarn test v0.27.5
$ mocha -r dotenv/config --recursive ./test dotenv_config_path=.env.test
Warning: Could not find any test files matching pattern: dotenv_config_path=.env.test


  env
    ✓ works

  doit
    ✓ works
    1) does not work


  2 passing (12ms)
  1 failing

  1) doit does not work:

      Error: Expected 123 to equal 321
      + expected - actual

      -123
      +321
      
      at assert (node_modules/expect/lib/assert.js:29:9)
      at Expectation.toEqual (node_modules/expect/lib/Expectation.js:81:30)
      at Context.it (test/app/doit.test.js:18:29)



error Command failed with exit code 1.
```

it works from command line as expected.

**Comment by nicck** [comment]
@maty21 please let me know if I can help with reproducing this issue or you need any more details.

**Comment by maty21** [comment]
Tks man I will debug it in the weekend :)

**Comment by yehiyam** [comment]
@nicck We need to figure out how to support dotenv, but as a workaround you could add the env from the file to `mocha.env` settings.
I was able to get your tests to run with these settings:
```javascript
{
    "mocha.requires": [
        "dotenv/config"
    ],
    "mocha.options": {
        "recursive":true
    },
    "mocha.env": {
        "NODE_ENV":"test",
        "OAUTH_CLIENT_ID":987
    }
}
```

**Comment by maty21** [comment]
fixed in version 0.14.30
