### ISSUE TITLE
"Test file(s): undefined"

### ISSUE THREAD

**Issue by jeff-kilbride** [maty21/mocha-sidebar#29]
Hi,

My test files show up in the sidebar, but when I try to `Run All Tests` I get the same type of error as in #13:
```
Running Mocha with Node.js at /Users/jeff/.nvm/versions/node/v8.9.1/bin/node

Applying Mocha options:
  {
    "ui": "bdd",
    "timeout": 10000,
    "recursive": true
  }

Test file(s):
  undefined
module.js:538
    throw err;
    ^

Error: Cannot find module '/Users/jeff/VSCode/api/src/undefined'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at /Users/jeff/.vscode/extensions/maty.vscode-mocha-sidebar-0.13.5/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/jeff/.vscode/extensions/maty.vscode-mocha-sidebar-0.13.5/node_modules/mocha/lib/mocha.js:217:14)
    at Mocha.run (/Users/jeff/.vscode/extensions/maty.vscode-mocha-sidebar-0.13.5/node_modules/mocha/lib/mocha.js:469:10)
    at Object.<anonymous> (/Users/jeff/.vscode/extensions/maty.vscode-mocha-sidebar-0.13.5/worker/runtest.js:63:7)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
```
I have the following config in my `User Settings`:
```
    "mocha.options": {
        "ui": "bdd",
        "timeout": 10000,
        "recursive": true
    },
    "mocha.files.glob": "test/**/*.js",
    "mocha.files.ignore": [
        "test/fixtures/**/*"
    ],
    "mocha.env": {
        "BLUEBIRD_DEBUG": "1",
        "BLUEBIRD_W_FORGOTTEN_RETURN": "0",
        "JWT_KEY": "XXXXX"
    },
    "mocha.node_options": [
        "--trace-warnings"
    ]
```
I am able to run my tests from the command line using both `nyc` and `mocha`:
```
$ yarn run test
yarn run v1.3.2
$ JWT_KEY=XXXXX nyc mocha


debug: -------------------------------------------------------
debug: :: Thu Nov 16 2017 15:49:01 GMT-0800 (PST)
debug: Environment : development
debug: Port        : 18888
debug: -------------------------------------------------------
  Controller: AdminController
    Route: GET /admin/alive
      ✓ should respond with an alive message

[ ... ]

  716 passing (9s)
  4 pending


=============================== Coverage summary ===============================
Statements   : 80.2% ( 3204/3995 )
Branches     : 67.07% ( 1167/1740 )
Functions    : 85.61% ( 595/695 )
Lines        : 80.84% ( 3131/3873 )
================================================================================
✨  Done in 11.05s.
```
But it seems like the `files` argument in `worker.js` is not being set correctly:
https://github.com/maty21/mocha-sidebar/blob/df46f1897903b788b8a9625e7b2c1209e6b240bf/worker/runtest.js#L45

Any help would be appreciated!

**Comment by maty21** [comment]
hi 
if you can upload not working sample it will be helpful coz i couldn't reproduce it on my tests

**Comment by jeff-kilbride** [comment]
I just tried setting a breakpoint at `line 45` inside the `worker.js` file. The breakpoint didn't work, but when I ran the command `Run Debug`, the tests all ran correctly:
```
Debugging with inspector protocol because Node.js v8.9.1 was detected.
node --inspect-brk=35669 ../../../../.vscode/extensions/maty.vscode-mocha-sidebar-0.13.5/node_modules/mocha/bin/_mocha test/**/*.js 
Debugger listening on ws://127.0.0.1:35669/65882198-48ca-47d0-85ac-c980a5938d85
Debugger attached.
debug: -------------------------------------------------------
debug: :: Fri Nov 17 2017 00:51:43 GMT-0800 (PST)
debug: Environment : development
debug: Port        : 18888
debug: -------------------------------------------------------
  Controller: AdminController
    Route: GET /admin/alive
      ✓ should respond with an alive message

[...]

  709 passing (11s)
  4 pending
  5 failing
```
The 5 failing tests are due to the environment variables not being set. So, something is different between the `Run All Tests` (not working) and `Run Debug` (working) commands.

It would be much easier if I could setup the debugger to step through the extension code, but I'm not sure how to do that. How can I get the VSCode debugger to recognize a breakpoint in the `worker.js` file? I'll try googling around a bit, but if you can point me in the right direction I'll take a look at it.

**Comment by maty21** [comment]
In order to debug it you have to do the follows
1. Uncomment if (debug) an all the relevant lines in fork.js
2. Set a breakpoint in fork.js  and debug your code  in the fork.js file
3.set the launch.json to debug your code
4. When breakpoint reached run attach node from my launch.json file

Let me know if you need anything

**Comment by jeff-kilbride** [comment]
Here's the output from the developer tools console:
```
[Extension Host] test arg: {"files":["undefined"],"options":{"ui":"bdd","timeout":10000,"recursive":true},"grep":null,"requires":[],"rootPath":"/Users/jeff/VSCode/api/src"}

console.ts:123 [Extension Host] module.js:538
    throw err;
    ^

Error: Cannot find module '/Users/jeff/VSCode/api/src/undefined'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at /Users/jeff/.vscode/extensions/maty.vscode-mocha-sidebar-0.13.5/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/jeff/.vscode/extensions/maty.vscode-mocha-sidebar-0.13.5/node_modules/mocha/lib/mocha.js:217:14)
    at Mocha.run (/Users/jeff/.vscode/extensions/maty.vscode-mocha-sidebar-0.13.5/node_modules/mocha/lib/mocha.js:469:10)
    at Object.<anonymous> (/Users/jeff/.vscode/extensions/maty.vscode-mocha-sidebar-0.13.5/worker/runtest.js:63:7)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)

t.log @ console.ts:123
t._logExtensionHostMessage @ extensionHost.ts:377
(anonymous) @ extensionHost.ts:202
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104

console.ts:123 [Extension Host] Error: unknown error
	at ChildProcess.process.on.on.code (/Users/jeff/.vscode/extensions/maty.vscode-mocha-sidebar-0.13.5/mochashim.js:104:18)
	at emitTwo (events.js:106:13)
	at ChildProcess.emit (events.js:194:7)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
t.log @ console.ts:123
t._logExtensionHostMessage @ extensionHost.ts:377
(anonymous) @ extensionHost.ts:202
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104

console.ts:123 [Extension Host] Unhandled Rejection at: Promise  Object {isFulfilled: false, isRejected: true, rejectionReason: Object}  reason:  Error: unknown error
	at ChildProcess.process.on.on.code (/Users/jeff/.vscode/extensions/maty.vscode-mocha-sidebar-0.13.5/mochashim.js:104:18)
	at emitTwo (events.js:106:13)
	at ChildProcess.emit (events.js:194:7)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```
As you can see in the first line, the `files` array is undefined. I haven't setup debugging, yet, but I will continue to play with it as I have time. 

I've also noticed that it's reloading the tests in the sidebar quite a lot. I have 700+ tests and the repeated reloading can slow the editor down quite a bit.

**Comment by maty21** [comment]
about your last comment you right there was unnecessarily  decoration updates on every file switches update it so only if a switch was done to a test file the decoration will update 
let me know if my fix in version 0.14.0 improve the performance

tks

**Comment by jeff-kilbride** [comment]
@maty21  It is a little bit better, but I still get a lot of updates in the developer tools console. When I make a change to a test file, I think it is re-loading all test files rather than just the one that has been changed. For example, I have created a gist of my developer tools console:

https://gist.github.com/jeff-kilbride/c8368a41ed519cca9450429a3a6848b8

All of these actions (nearly 6000 lines) took place when I did two things:
- Add a blank line to an open test file
- Click on the developer tools window (change focus from the editor)

The change of focus from the editor to the developer tools console comes at line 2823. You can see from the timestamps that I am getting thousands of updates per second. This happens whenever I make a change to a test file. For the one to two seconds it takes for these actions to run, my cursor slows down or stops responding altogether. It makes editing test file very difficult. It is better than it was, because I believe this was happening for all files before your latest change.

Would it be possible to limit these updates to only the test file being edited?

Also, I am seeing this error quite a bit, too:
```
shell.ts:459 [maty.vscode-mocha-sidebar] Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined
	at files.forEach.f (/Users/jeff/.vscode/extensions/maty.vscode-mocha-sidebar-0.14.0/changesNotification.js:44:90)
	at Array.forEach (native)
	at Glob (/Users/jeff/.vscode/extensions/maty.vscode-mocha-sidebar-0.14.0/changesNotification.js:43:27)
	at f (/Users/jeff/.vscode/extensions/maty.vscode-mocha-sidebar-0.14.0/node_modules/once/once.js:25:25)
	at Glob.<anonymous> (/Users/jeff/.vscode/extensions/maty.vscode-mocha-sidebar-0.14.0/node_modules/glob/glob.js:151:7)
	at emitOne (events.js:96:13)
	at Glob.emit (events.js:191:7)
	at Glob._finish (/Users/jeff/.vscode/extensions/maty.vscode-mocha-sidebar-0.14.0/node_modules/glob/glob.js:197:8)
	at done (/Users/jeff/.vscode/extensions/maty.vscode-mocha-sidebar-0.14.0/node_modules/glob/glob.js:182:14)
	at Glob._processGlobStar2 (/Users/jeff/.vscode/extensions/maty.vscode-mocha-sidebar-0.14.0/node_modules/glob/glob.js:637:12)
	at /Users/jeff/.vscode/extensions/maty.vscode-mocha-sidebar-0.14.0/node_modules/glob/glob.js:626:10
	at RES (/Users/jeff/.vscode/extensions/maty.vscode-mocha-sidebar-0.14.0/node_modules/inflight/inflight.js:31:16)
	at f (/Users/jeff/.vscode/extensions/maty.vscode-mocha-sidebar-0.14.0/node_modules/once/once.js:25:25)
	at lstatcb_ (/Users/jeff/.vscode/extensions/maty.vscode-mocha-sidebar-0.14.0/node_modules/glob/glob.js:519:7)
	at RES (/Users/jeff/.vscode/extensions/maty.vscode-mocha-sidebar-0.14.0/node_modules/inflight/inflight.js:31:16)
	at f (/Users/jeff/.vscode/extensions/maty.vscode-mocha-sidebar-0.14.0/node_modules/once/once.js:25:25)
```
This seems to happen whenever I close an editor window, both for test files an non-test files.

**Comment by maty21** [comment]
just add a patch for issue #30 let me no if it fixes  the "document " exception 

tks

**Comment by jeff-kilbride** [comment]
I no longer get that error:
```
[Extension Host] notification:editor is not defined therefore tests will not updates 
                     please refresh it manually via side bar 
```
👍
