### ISSUE TITLE
Sidebar failed to load tests

### ISSUE THREAD

**Issue by thyagab** [maty21/mocha-sidebar#39]
I have mochajs project with bable transpiler.
When i install mocha-sidebar in vscode, tests are not showing up.
api-test(root folder)/smoke-test/smoke.js is my test location.
When I change test location to this, it give me error
"Mocha sidebar: Process exited with code 255. See Mocha output for more info."
when i check mocha output, it says Finding tests with Mocha on Node.js at "/usr/local/bin/node"
I have set my settings as
{"mocha.options": {
		"compilers": {
			"js": "./custom-babel-register.js"
		  }
		},
		"mocha.requires": [
			"babel-polyfill"
		],
		"mocha.files.glob": "api-tests/smoke/*.js"
	}

**Comment by maty21** [comment]
If you can share a code it will be nice I will debug it for you

**Comment by thyagab** [comment]
[mocha-sidebar.zip](https://github.com/maty21/mocha-sidebar/files/1564893/mocha-sidebar.zip)
Here is the project.

**Comment by maty21** [comment]
tks :)

**Comment by thyagab** [comment]
Is there any workaround or can be fixed in forked branch for my use?

**Comment by maty21** [comment]
Hi man I'll try to fix it in the weekend

**Comment by maty21** [comment]
it works for me when i added  "babel register" to the require please  check if it works for you 
 your configuration should be 

```json
   "mocha.options": {
        "compilers": {
            "js": "./custom-babel-register.js"
        }
    },
    "mocha.requires": [
        "babel-polyfill",
        "babel-register"
    ],
    "mocha.files.glob": "api-tests/smoke/*.js"
```

**Comment by thyagab** [comment]
Thank you. It worked. But came across other issue when loading other file

[Extension Host] get Children: 0
messageService.ts:126 Cannot read property 'forEach' of undefined: TypeError: Cannot read property 'forEach' of undefined
	at mochaProvider._createTreeFromArray (/Users/tatthipatla/.vscode/extensions/maty.vscode-mocha-sidebar-0.14.16/mochaProvider.js:49:20)
	at mochaProvider.loadAndFormatTests (/Users/tatthipatla/.vscode/extensions/maty.vscode-mocha-sidebar-0.14.16/mochaProvider.js:92:35)
	at <anonymous>
e.doShow @ messageService.ts:126
e.show @ messageService.ts:105
(anonymous) @ mainThreadTreeViews.ts:70
v @ winjs.base.raw.js:1209
enter @ winjs.base.raw.js:901
_run @ winjs.base.raw.js:1068
_error @ winjs.base.raw.js:1041
e.resolveErr @ lazyPromise.ts:78
e._receiveOneMessage @ rpcProtocol.ts:68
(anonymous) @ rpcProtocol.ts:32
(anonymous) @ rpcProtocol.ts:157
e.fire @ event.ts:142
(anonymous) @ ipc.net.ts:81
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
log.ts:165   ERR Please return an array of children.: Error: Please return an array of children.

**Comment by maty21** [comment]
did you tried to run your code via mocha without the extension

**Comment by thyagab** [comment]
yes without extension it runs fine. I am suspecting it is failing in finding tests during format test steps.

**Comment by thyagab** [comment]
Tried to debug it at the stage of create mocha, it was able find tests
createMocha(args.rootPath, args.options, args.files.glob, args.files.ignore)
  .then(mocha => crawlTests(mocha.suite))
  .then(tests => {
    console.error(JSON.stringify(tests, null, 2))

after that it is failing. 

    async loadAndFormatTests() {
        this._tests = await this._runner.loadAsyncTestFiles();
        console.log('this._tests',this._tests)
        this._formatedTest = this._createTreeFromArray();
    }
At this point this._tests is coming as null.

**Comment by thyagab** [comment]
observed following errors as well in console 

mainThreadExtensionService.ts:44 ReferenceError: stderrBuffers is not defined
	at Socket.forkFindTests.then.process.stderr.on.data (/Users/tatthipatla/.vscode/extensions/maty.vscode-mocha-sidebar-0.14.16/mochashim.js:174:9)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)

**Comment by maty21** [comment]
If you have any sample to share it will be helpful I'll debug it  tks :)

**Comment by tanglebones** [comment]
I have a similar issue, using ```"mocha.files.glob": "src/**/*.test.js",``` results in a ```Cannot read property 'forEach' of undefined: TypeError: Cannot read property 'forEach' of undefined``` error and not tests appearing. (We use companion ```.test.js``` files instead of a test directory.

**Comment by maty21** [comment]
And it works if you remove the .test ?

**Comment by thyagab** [comment]
[mocha-sidebar.zip](https://github.com/maty21/mocha-sidebar/files/1581399/mocha-sidebar.zip)
I had created junk tests to recreate the problem.

**Comment by maty21** [comment]
working for me using this configuration 
```js
{
    "mocha.options": {
        "compilers": {
            "js": "./custom-babel-register.js"
        },
    },
    "mocha.requires": [
        "babel-polyfill",
        "babel-register"
    ],
    "mocha.files.glob": "api-tests/*/*.js"
}
```

did i missed something ?

![image](https://user-images.githubusercontent.com/5236665/34317967-be41a78c-e75f-11e7-9a16-176b6cd68ff7.png)

**Comment by thyagab** [comment]
I am using same settings and in my mac it is failing. I am able to execute using terminal.
<img width="1440" alt="screen shot 2017-12-23 at 9 06 35 am" src="https://user-images.githubusercontent.com/19270843/34321303-afef6cb2-e7c0-11e7-9a69-92883782277a.png">

**Comment by maty21** [comment]
I will try to reproduce it on Mac maybe it's related to the os don't have
other clue

**Comment by thyagab** [comment]
can you help me debug on my side? when i try to debug extension the workspace settings are not loaded.I tried enabling the breakpoints by un commenting forks.js but nothing is happening.

**Comment by maty21** [comment]
You have  to attach other process because we running mocha in other process in order to be decoupled from vscode node version.
  I will add something today so it will be easier to debug it and I I'll also add instructions how to do it in the contribution guide

**Comment by andrioli** [comment]
I got the same error here. But with TypeScript tests. 

My `settings.json` is:
```json
{
    "mocha.files.glob": "test/*.ts",
    "mocha.options": {
        "compilers": {
            "ts": "ts-node/register"
        }
    },
    "mocha.requires": [
        "ts-node/register"
    ],
}
```

The erro is: **Cannot read property 'forEach' of undefined**

I manually run the tests from console with command `mocha -r ts-node/register test/*.ts`.

mocha, ts-node and typescript dependencies are installed locally.

**Comment by maty21** [comment]
The foreach of undefined means that mocha parser for some reason couldn't
find tests
 it could be happen from many reasons in must of the cases is bad
configuration in order to test it I need sample to debug thanks :)

**Comment by andrioli** [comment]
@maty21 I was trying to create a reproducer, but I could not reproduce with a simple and small test file. After a while I was able to reproduce with a test file with one `describe` function and thirty-five `it` functions. Really weird. Also looks that the error is not deterministic, some times with fewer `it` functions the error appears.

When I open VS code with the buggy test file the following messages shows up in developer tools console:
![screen shot 2017-12-31 at 4 34 13 pm](https://user-images.githubusercontent.com/499182/34463621-ff7c6df0-ee48-11e7-90b9-aa35c5d95c02.png)

After delete a single `it` function everything works fine. And when I add a new one everything breaks again with the following messages in developer tools console:
![screen shot 2017-12-31 at 4 42 58 pm](https://user-images.githubusercontent.com/499182/34463633-b71a3046-ee49-11e7-9d32-f5c55c65ae89.png)

I'm not sure, not looked the code, but the log messages suggest me a timeout in a promise function.

I hope this can help. 

Happy new year!

**Comment by thyagab** [comment]
@maty21 Any update on this issue? Were you able to add the debug instructions?

**Comment by maty21** [comment]
Today :)

**Comment by maty21** [comment]
just added it under the contribution guide [CONTRIBUTING.md](https://github.com/maty21/mocha-sidebar/blob/master/CONTRIBUTING.md) let me know if you need any help

**Comment by thyagab** [comment]
Tried debugging not sure if the following error is relevant
Error [undefined]: channel closed
    at process.target.send (internal/child_process.js:588:16)
    at createMocha.then.then.tests (/Users/jim/extension/mocha-sidebar/worker/findtests.js:25:13)
    at tryCatcher (/Users/jim/extension/mocha-sidebar/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/jim/extension/mocha-sidebar/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/jim/extension/mocha-sidebar/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/jim/extension/mocha-sidebar/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/jim/extension/mocha-sidebar/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/jim/extension/mocha-sidebar/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/jim/extension/mocha-sidebar/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/jim/extension/mocha-sidebar/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

**Comment by thyagab** [comment]
@maty21 Does the above error could cause that error?

**Comment by maty21** [comment]
Imo it not here co that line related to the sending data from the fork so it not sounds to me the issue try to place a breakpoint inside the findtest file and see what happens there

**Comment by derwaldgeist** [comment]
I'm having the same problem on my Mac. Here's how I used to call mocha via package.json:

```
"test": "mocha --compilers js:babel-core/register -r jsdom-global/register"
```

How would that be translated into the correct mocha options?

**Comment by derwaldgeist** [comment]
Here's the error I'm getting in the console:

```

log.ts:165   ERR Please return an array of children.: Error: Please return an array of children.
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:299:343
    at Object.g [as _notify] (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:139:729)
    at Object.enter (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:143:568)
    at n.Class.derive._oncancel._run (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:144:866)
    at n.Class.derive._oncancel._error (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:144:383)
    at e.resolveErr (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2588:306)
    at e._receiveOneMessage (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2589:682)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2589:10
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2590:913
    at e.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:159:872)
```

**Comment by maty21** [comment]
It's seems like that your settings are incorrect did you try to set it as written in the readme ? About the glob pattern you have to set the first ancestor path in order to see all the tests

**Comment by thyagab** [comment]
@maty21 I already tried with a breakpoint in findtests and tests are passed correctly to send tests call and it is failing at different places. Not sure it is something to do with memory. Here is the next thing I see in console. Not able to debug further.

/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:1225   ERR Please return an array of children.: Error: Please return an array of children.
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:299:343
    at Object.g [as _notify] (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:139:729)
    at Object.enter (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:143:568)
    at n.Class.derive._oncancel._run (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:144:866)
    at n.Class.derive._oncancel._error (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:144:383)
    at e.resolveErr (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2588:306)
    at e._receiveOneMessage (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2589:682)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2589:10
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2590:913
    at e.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:159:872)
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4056 [maty.vscode-mocha-sidebar]Cannot read property 'doneAmount' of null
e.$onExtensionRuntimeError @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4056
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4056 TypeError: Cannot read property 'doneAmount' of null
	at callDone (/Users/tatthipatla/work/automation/extension/mocha-sidebar/node_modules/await-done/lib/await-done.js:7:33)
	at vscode.debug.onDidTerminateDebugSession.ev (/Users/tatthipatla/work/automation/extension/mocha-sidebar/provider-extensions/runDebug.js:120:5)
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:87:218)
	at e.$acceptDebugSessionTerminated (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:422:198)
	at t.e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:516:87)
	at e._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:357:580)
	at e._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:357:270)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:356:206
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:358:204
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:85:988
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:87:218)
	at Socket.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:135:717)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)
e.$onExtensionRuntimeError @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4056

**Comment by lockhart5** [comment]
Have the same "Cannot read property 'forEach' of undefined", I think it has something to do with a limit on how many test files can be loaded, which looks to be only 9.  I have 10+ *.test.js files renamed them all to *.test.js1 and then renamed one by one back to .js.  When there is < 9 .js files, is fine, 10+ is not.  Doesn't matter which files or the order I rename them, but only ever can get 9 to load properly.

**Comment by maty21** [comment]
We tested it with much more tests than 10 and it works without any problem
so it something else with your first 9 it works for you ?

**Comment by thyagab** [comment]
@maty21 Have you checked in mac? Also does the error posted above an issue? Not able to figure it out. Will not be able to use the extension.

**Comment by lockhart5** [comment]
@maty21 Yeah, I don't know then.  I am on a Mac.  I have a different project with only one file and it works great with the same settings.  The 9 limit thing just seemed weird since I could reproduce it with any combination files and that seemed to be the only constant.  Pasted the console message below if that helps.  Let me know if you want me to try anything else.

Cannot read property 'forEach' of undefined: TypeError: Cannot read property 'forEach' of undefined
	at mochaProvider._createTreeFromArray (/Users/ryanlockhart/.vscode/extensions/maty.vscode-mocha-sidebar-0.14.18/mochaProvider.js:49:20)
	at mochaProvider.loadAndFormatTests (/Users/ryanlockhart/.vscode/extensions/maty.vscode-mocha-sidebar-0.14.18/mochaProvider.js:92:35)
	at <anonymous>

ERR Please return an array of children.: Error: Please return an array of children.
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:299:343
    at Object.g [as _notify] (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:139:729)
    at Object.enter (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:143:568)
    at n.Class.derive._oncancel._run (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:144:866)
    at n.Class.derive._oncancel._error (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:144:383)
    at e.resolveErr (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2588:306)
    at e._receiveOneMessage (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2589:682)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2589:10
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2590:913
    at e.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:159:872)

**Comment by andrioli** [comment]
I still think that is some issue with a timeout as pointed in my previous comment https://github.com/maty21/mocha-sidebar/issues/39#issuecomment-354618799. The timeout "can" explain the randomness of the bug in different machines. May also be something specific to MacOS. I'll try to debug today in my machine.

**Comment by andrioli** [comment]
@maty21 Just found some thing that is related to the bug. Looks that the problem is in the IPC. For some reason, for buggy classes, when `findtests.js` calls `process.send(tests)` with the found tests, the event handler on `mochashim.js` receives `undefined`. Changing the `findtests.js` to call `console.log(tests)` instead of `process.send(tests)` and invoking the script from my shell prints the expected output.

Maybe is something related to buffers? IDK how process communications works on Node.

**Comment by yehiyam** [comment]
I think I solved it. It seems that there was a race condition between process.send and process.exit. I added a callback to wait for the end of the send before exiting the process.
Later I will publish a new version

**Comment by yehiyam** [comment]
Published the new version. Please update and see if it works

**Comment by lockhart5** [comment]
@yehiyam That did it, all good now...thank you.

**Comment by andrioli** [comment]
@yehiyam Great. Is working for me now! Thanks

**Comment by maty21** [comment]
Great it seems like that the bug solved 
I'm closing it btw love the extension 🌟 us  :)

**Comment by maty21** [comment]
Great it seems like that the bug solved 
I'm closing it btw love the extension 🌟 us  :)

**Comment by maty21** [comment]
Great it seems like that the bug solved 
I'm closing it btw love the extension 🌟 us  :)

**Comment by maty21** [comment]
Great it seems like that the bug solved 
I'm closing it btw love the extension 🌟 us  :)

**Comment by maty21** [comment]
Great it seems like that the bug solved 
I'm closing it btw love the extension 🌟 us  :)

**Comment by thyagab** [comment]
Finally it worked. Thank @maty21 @yehiyam for fixing this issue.
