### ISSUE TITLE
Cannot run mocha-sidebar with typescript ts-node

### ISSUE THREAD

**Issue by ahmadkhudeish** [maty21/mocha-sidebar#61]
Hi there, 

When I try to run the tests using mocha sidebar it just doesn't read show my tests.
In the output tab I get this **Finding tests with Mocha on Node.js at "/usr/bin/node"**

And I also get the error **Mocha sidebar: Process exited with code 1. See Mocha output for more info.**

My workspace settings look like this:

`  
 "mocha.files.glob": "src/**/*.spec.ts",
  "mocha.options": {
    "compilers": {
      "ts": "ts-node/register"
    }
  },
  "mocha.requires": [
      "ts-node/register"
  ],
  "mocha.runTestsOnSave": "true"
`

I have typescript installed locally
I have all my unit tests under src directory.

Is there any docs I can refer to for Typescript setup with ts-node?

Thanks
Ahmad

**Comment by maty21** [comment]
Your test location  matches  files.glob settings 

You can run your tests via command line ?

**Comment by ahmadkhudeish** [comment]
Yes I can run the tests fine using the command-line. 

Is it something wrong with my files.glob settings?

**Comment by yehiyam** [comment]
hi @ahmadkhudeish  
It works for me with these settings:
`
"mocha.options": {  
        "compilers": "ts-node/register"  
    }, 
    "mocha.requires": [ 
        "ts-node/register" 
    ], 
    "mocha.files.glob": "test/*.test.ts" 
`

**Comment by ahmadkhudeish** [comment]
Well that looks exactly the samr as mine isnt it exxcept mine is pointing to a different directory. My files are stored inside src/modules/inventories/tests/test1.spec.ts.

Shouldn't my mocha.files.glob be able to recognise that directory and execute the tests? 

I'm confused

**Comment by maty21** [comment]
Try to set the full path and see if it works for you

**Comment by ahmadkhudeish** [comment]
I tried to set the full path but no luck, still not working. 
Has this package been tested with path different than test/*.test.ts?

**Comment by yehiyam** [comment]
Could you try to set the compilers option like I did. Without the ts:

On Feb 14, 2018 22:38, "Ahmad Khudeish" <notifications@github.com> wrote:

I tried to set the full path but no luck, still not working.
Has this package been tested with path different than test/*.test.ts?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/maty21/mocha-sidebar/issues/61#issuecomment-365737775>,
or mute the thread

**Comment by ahmadkhudeish** [comment]
I did change it, and still the same issue I get the error **Mocha sidebar: Process exited with code 1. See Mocha output for more info.**

Any ideas? Thanks

**Comment by maty21** [comment]
Just added more informative error message

**Comment by RikkiGibson** [comment]
I was able to make it work with only the following additions to `settings.json` in my project:
```json
{
  "mocha.files.glob": "./test/**/*.ts",
  "mocha.requires": ["ts-node/register"]
}
```

**Comment by zengming00** [comment]
I have same problem, got a error
```
"TypeError: Cannot convert undefined or null to object
	at Function.keys (<anonymous>)
	at mochaLens._getRelevantItems (C:\Users\zengming\.vscode\extensions\maty.vscode-mocha-sidebar-0.17.5\provider-extensions\mochaLens.js:158:16)
	at mochaLens.provideCodeLenses (C:\Users\zengming\.vscode\extensions\maty.vscode-mocha-sidebar-0.17.5\provider-extensions\mochaLens.js:48:49)
	at <anonymous>"
```

**Comment by zengming00** [comment]
i just uninstall, and reintall it , it work!  this is my config
```
    "mocha.files.glob": "test/**/*.ts",
    "mocha.requires": [
        "ts-node/register"
    ],
    "mocha.options": {
        "compilers": {
            "ts": "ts-node/register"
        }
    }
```

**Comment by PandaWood** [comment]
I have the same config as @zengming00 and the tests are now found, and they seem to run (as indicated by the footer bar saying "Tests 5 0" but there's no output anywhere except this every time in the "Mocha output"

```
trying to searching for tests using these settings: 

    mocha path: mocha
    test files location: **/*.spec.ts
    files to ignore: **/.git/**/*,**/node_modules/**/*
    environmets: {}
    requires: ["ts-node/register"]
    options:  {"compilers":{"ts":"ts-node/register"}}
```

**Comment by yehiyam** [comment]
@PandaWood you can see the test result in the output if you set mocha.logVerbous to true in the settings

**Comment by PandaWood** [comment]
Thanks that does it

**Comment by HeavyStorm** [comment]
It took me a while but I got it running.

I have no idea what was wrong, actually, but in the end my config is:
```js
"mocha.files.glob": "**/*.spec.ts",
	"mocha.requires": [
		"ts-node/register"
    ],
```

I think what did the trick was no specifying the directory in mocha.files.glob, instead, going directly with the recursion.

**Comment by sparkydasrath** [comment]
All
I am also having the same issue as outlined above. In my .vscode folder, I created a settings.json which generated a ton of settings stuff. The workspace tab was empty and I added what @zengming00 has but changed to fit my project:

`{
    "mocha.files.glob": "test/**/*.spec.ts",
    "mocha.requires": [
        "ts-node/register"
    ],
    "mocha.options": {
        "compilers": {
            "ts": "ts-node/register"
        }
    }
}`

I have a very simple test called app.spec.ts located at test/ts/app.spec.ts. Even with the settings above, I do not get the gitlens hit to run all tests and my sidebar is blank. I even tried a reinstall of the plugin but no dice.

in the sidebar-mocha output I get:

`trying to searching for tests using these settings: 

    mocha path: mocha
    test files location: test/**/*.ts
    files to ignore: **/.git/**/*,**/node_modules/**/*
    environmets: {}
    requires: ["ts-node/register"]
    options:  {"compilers":{"ts":"ts-node/register"}}
`
I am not sure why _mocha.files.glob_ and _test files location_ do not match.

I was able to get mocha running via a gulp task, but getting the sidebar setup would be excellent. This thread is the closest I have come across that seems to have a working answer. Any assistance will be greatly appreciated.

**Comment by maty21** [comment]
Do my best to fix it for you guys in this week

**Comment by linvi** [comment]
I had the same issue and I made it work after the reinstalling the extension.
I also use the same configuration as @HeavyStorm.

Now even though the sidebar properly detects the tests, the `Run Test` and `Debug Test` that I can usually see test file are no longer available.

![screen shot 2018-07-20 at 11 47 05](https://user-images.githubusercontent.com/6107439/42998643-bc117f2a-8c12-11e8-9e73-c6a164359ceb.png)

**Comment by sparkydasrath** [comment]
@maty21 
Just to let you know, I saw there was an update to the sidebar, got it and no luck. Uninstalled-reinstalled and still nothing. The only change I made since my last post was the workspace settings to do recursive lookup:

`{
    "mocha.files.glob": "**/*.spec.ts",
    "mocha.requires": [
        "ts-node/register"
    ],
    "mocha.options": {
        "compilers": {
            "ts": "ts-node/register"
        }
    },
}`

The tests are still not showing up in the sidebar. In the **offchance** there is something wrong with the test file itself, here is one example:

`import { assert } from "chai";
import { StringUtility } from "../../src/ts/StringUtility"

describe("StringUtility Tests\t", () => {
    it("Should replace + in the string with -", () => {
        let baseString = "1 + ";
        let replacement = "-";
        let result = StringUtility.replaceAt(baseString, replacement, baseString.length - 2);
        assert.equal(result, "1 - ")
    });
});`

Let me know if I can provide anything else to help sort this out.

Thanks for your work as always.

**Comment by maty21** [comment]
Hi try remove options  also
 what is ts-node package version

**Comment by sparkydasrath** [comment]
@maty21 

`"ts-node": "^7.0.0",`

Additionally, I removed the options section from the settings so all I have left is:
`{
    "mocha.files.glob": "**/*.spec.ts",
    "mocha.requires": [
        "ts-node/register"
    ],
}`

Uninstalled and reinstalled the sidebar but still nothing. Sorry.

**Comment by maty21** [comment]
- What is the error u get ?
- I assume u can run it via cli , what is the command u running ?
- Can u send a sample of a not working porject so I will be able to debug it for u ?

**Comment by maty21** [comment]
Another thing 
I just added a sample of a working project under the test folder can u please try clone and run it so we can verify that there is no something that went wrong on your pc

**Comment by linvi** [comment]
@maty21 I wanted to let you know that I actually uninstalled the extension because the only way I managed to make it work was to uninstall / install the extension each time the VSCode was restarting.

After a new install, the extension managed to list the tests.
After a restart of VSCode the extension was not finding any of the tests anymore (no change anywhere).

Also, the extension is opening error notifications constantly when you dev with TS.
I think the reason is that when you type, the extension/mocha is running being executed, which result in ts-node to try to compile the code which result in a crash if you are in a middle of a change (you do not need to save a file for the notification to popup).

I hop this helps you.

**Comment by maty21** [comment]
hi @linvi 
 I couldn't reproduce your issue can you explain more about what u think that can cause the problem. 
also, can you try test [https://github.com/maty21/mocha-sidebar/tree/master/test/typeScript-test](https://github.com/maty21/mocha-sidebar/tree/master/test/typeScript-test) this sample on your pc i tried to restart vscode couple of times and its working for me tks a lot for your support

**Comment by maty21** [comment]
Same as in the README file am I right ?

**Comment by maty21** [comment]
@yagasoft try remove option it's not needed , also what is the mocha  cli command you running ?

**Comment by yagasoft** [comment]
Going back to Node 8 made it work. Thank you :).

**Comment by maty21** [comment]
Nice :)

**Comment by simpert** [comment]
## Mocha Sidebar extension does not find and load tests in sidebar panel.

I am using the typical configuration in settings file and write a simple spec file for testing.
The output does not show anything helpful.

## Here is my configuration and environemnt
**Node**  
- 10.7.0.

**VS Code**
![image](https://user-images.githubusercontent.com/2422222/43752220-6a190edc-99bd-11e8-9d3d-299d6bdff0a4.png)

**Mocha Sidebar Output**  
```
____________________________________________________________________________
trying to searching for tests using these settings: 

    mocha path: mocha
    test files location: ./test/*.spec.{ts,tsx}
    files to ignore: **/.git/**/*,**/node_modules/**/*
    environmets: {}
    requires: ["ts-node/register","ignore-styles","jsdom-global/register","jquery"]
    options:  {}
if you find anything wrong please change those default settings
____________________________________________________________________________
data send to parent. Exiting.
```  

**setting.json**
```
    "mocha.files.glob": "./test/*.spec.{ts,tsx}",
    "mocha.requires": [
        "ts-node/register",
        "ignore-styles",
        "jsdom-global/register",
        "jquery"
    ],
    "mocha.logVerbose": true
```  
**test spec file**
```
import * as chai from 'chai';

var expect = chai.expect;

beforeEach( function ()
{
    console.log( 'beforeEach hook' );
} );

describe( "mockTest -> return true", () =>
{
    it( 'should allways assert true', () =>
    {
        expect( true ).is.not.null;
    } );
} );
```  
## A possible solution
I did get the panel to work by installing a older version **node 7.7.4**. Out of a hunch I simply ran `nvm install 7.7.4` then loaded it, then restarted `VS Code` and the panel started to recognize the tests and eveything appeard to be working. 

> *node v7.7.4 was just a random older version I installed to test with*.  

However, I am unable to use that version of `node`.


### results
I spent hours attempting everything in this issue to no avail. 
Surprisingly, on my work PC the same project's in VS Code the extension works as expected.

Here is the sidebar panel
![image](https://user-images.githubusercontent.com/2422222/43752515-98ef8c76-99be-11e8-84c0-2a0494651967.png)

# Further:
upon simply opening workspace in `VS Code` and opening the developer debugger tools, I notice several errors in console.

Here is the most prominent one. I was receiving much different errors before I switched node version to `7.7.4` then back to `10.8.0`.
```
[Extension Host] notification: timeout reached activating and set time out to active again
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1376   ERR Cannot read property 'passed' of undefined: TypeError: Cannot read property 'passed' of undefined
	at _mochaProvider.onDidChangeTreeData (C:\Users\tommy\.vscode\extensions\maty.vscode-mocha-sidebar-0.20.17\extension.js:181:56)
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:97:917)
	at mochaProvider.refreshExplorer (C:\Users\tommy\.vscode\extensions\maty.vscode-mocha-sidebar-0.20.17\mochaProvider.js:99:35)
	at Timeout.setTimeout [as _onTimeout] (C:\Users\tommy\.vscode\extensions\maty.vscode-mocha-sidebar-0.20.17\changesNotification.js:93:57)
	at ontimeout (timers.js:386:14)
	at tryOnTimeout (timers.js:250:5)
	at Timer.listOnTimeout (timers.js:214:5)
```  

I don't know if it's related or not.

I hope this info helps to resolve issues.
Thanks for the wonderful extension it truly is great when working as expected.

> If there is any other information you need from me please let me know and I'll do my best.

**Comment by maty21** [comment]
Thanks for this information can you please tell me what are the differences between the two PC's . OS , vscode version, node version , vscode version.... Thanks

**Comment by simpert** [comment]
Sure,

My work PC is a desktop running Window 10 Pro.
My other is a Microsoft Surface Pro 3 running Windows 10 Pro.

So my work PC is running node version 8.11.1. I didn’t try this same version of node on my Surface. I was just starting a new Electron project Today and it requires a newer version of node.

VS Code version’s are the same.

I think there is a problem only when using newer versions of node. I have not tried many versions to test this. I just tried to install the latest with nvm and it failed to install npm correctly so I went back to 10.7.0.

I am using Nvm for Windows. The command ‘nvm install latest -arch 64` is the command that fails to install npm right. Weird.

I am pretty new to using node. My work PC running 8.11.1 with the project that the sidebar works as expected in has not tried this new project I was creating Today.

Tomorrow I will try to install newer node on my work pc and will get back to you.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by maty21** [comment]
Thanks man

**Comment by maty21** [comment]
hi 
I believe u have to have to update node-ts version to the latest version.
I was able to reproduce it then updated ts-node to the latest 7.0.1 
and its working
please  try to update, let me know if you still have problems

**Comment by lrpinto** [comment]
I followed the solutions suggested. Sadly, could not make it work. The side bar simply shows blank. The debug console shows no error. I gave up and for now just set the glob pointing at 

```
  "mocha.files.glob": "dist/__tests__/**/*.js"
```

I have .ts compilation running on watch mode as well, so that any changes in my .ts code update the sidebar tests straight way. Like this  can make use of the sidebar to run and debug the tests. 

It is only a little annoying to change between the .ts and .js versions between debugging and making changes. But it is the best I could achieve for now. I will follow this thread hoping to hear about a fix. Thanks for the great work.

**Comment by lrpinto** [comment]
Actually, I made some progress with regard to `.ts` tests being discovered. The issue is that they do not run. It is not a test issue, because if I use the `.js` tests directly, as explained in my above comment, the test runs fine.

**Mocha Sidebar with `.ts` Files Discovered - Test Fails**

![image](https://user-images.githubusercontent.com/2735779/98482084-bc509080-21f6-11eb-8b6b-77a7bf07c244.png)

**Mocha Sidebar with `.js` Files Discovered - Test Passes**

![image](https://user-images.githubusercontent.com/2735779/98482168-8364eb80-21f7-11eb-91c2-d24604cc3971.png)

**VSCode Config Used for `.ts` Files**
```
  "mocha.files.glob": "src/__tests__/**/*.ts",
  "mocha.requires": [ "ts-node/register"]
```

**VSCode Config Used for `.js` Files**
```
  "mocha.files.glob": "dist/__tests__/**/*.js",
```

I hope this helps track down the issue, to reproduce simply create a loopback 4 app, and then run the Ping test in `.ts` and `.js` mode. In `.ts` mode the test fails, whereas it runs in `.js` mode passes. 

Oh another detail that might be useful I am running VS Code Windows, via WSL Ubuntu.

**Comment by jahanalem** [comment]
Hello,
How can I solve this problem?
[https://stackoverflow.com/q/68004071/1817640](https://stackoverflow.com/q/68004071/1817640)

**Comment by Splines** [comment]
@jahanalem I use the [Mocha Test Explorer extension](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-mocha-test-adapter) and encountered the same problem. Finally, it works for me now, **I've written down my answer [here](https://stackoverflow.com/a/71452463/9655481)**. Maybe this is still useful for users of this extension, but haven't tried it. The answer might be especially useful if you use a folder structure where you have a kind of `backend` folder, resulting in the `test` folder not being located in the root of your project folder. **TL;DR: setup a multi-root workspace in VSCode.**
