### ISSUE TITLE
Bizarre behavior when expanding and collapsing test sections

### ISSUE THREAD

**Issue by jreina** [maty21/mocha-sidebar#79]
A few observations:
1. Sometimes sections don't show any tests
1. Sometimes sections show fewer tests than exist in that section
1. Sometimes when expanding a section a single test will appear at the bottom of the list of sections
1. Sections disappear when collapsing sections that appear in the list before it

I am at a loss for what could be causing this. I will try to put together a way to reproduce the issue but the sidebar is unusable for me at the moment.

**Comment by jreina** [comment]
Here is some logging 
```
[2018-03-13 16:25:18.762] [renderer5] [error] Cannot read property 'number' of undefined: TypeError: Cannot read property 'number' of undefined
	at mochaLens.lensTestDebugCreator (C:\Users\jreina\.vscode\extensions\maty.vscode-mocha-sidebar-0.14.34\provider-extensions\mochaLens.js:100:58)
	at mochaLens.createLensItemFromTree (C:\Users\jreina\.vscode\extensions\maty.vscode-mocha-sidebar-0.14.34\provider-extensions\mochaLens.js:146:30)
	at Object.keys.forEach.k (C:\Users\jreina\.vscode\extensions\maty.vscode-mocha-sidebar-0.14.34\provider-extensions\mochaLens.js:123:33)
	at Array.forEach (native)
	at mochaLens.createLensFromTree (C:\Users\jreina\.vscode\extensions\maty.vscode-mocha-sidebar-0.14.34\provider-extensions\mochaLens.js:121:27)
	at Object.keys.forEach.k (C:\Users\jreina\.vscode\extensions\maty.vscode-mocha-sidebar-0.14.34\provider-extensions\mochaLens.js:134:22)
	at Array.forEach (native)
	at mochaLens.createLensFromTree (C:\Users\jreina\.vscode\extensions\maty.vscode-mocha-sidebar-0.14.34\provider-extensions\mochaLens.js:121:27)
	at Object.keys.forEach.k (C:\Users\jreina\.vscode\extensions\maty.vscode-mocha-sidebar-0.14.34\provider-extensions\mochaLens.js:134:22)
	at Array.forEach (native)
	at mochaLens.createLensFromTree (C:\Users\jreina\.vscode\extensions\maty.vscode-mocha-sidebar-0.14.34\provider-extensions\mochaLens.js:121:27)
	at mochaLens.provideCodeLenses (C:\Users\jreina\.vscode\extensions\maty.vscode-mocha-sidebar-0.14.34\provider-extensions\mochaLens.js:51:18)
	at <anonymous>
[2018-03-13 16:25:19.783] [renderer5] [error] Cannot read property 'filter' of undefined: TypeError: Cannot read property 'filter' of undefined
    at t.hasToAlignWithTwisty (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4000:34)
    at t.alignByTheme (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3999:610)
    at t.align (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3999:493)
    at e.renderElement (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3998:656)
    at e.render (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:426:26)
    at e.insertInDOM (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:426:462)
    at t.insertItemInDOM (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:453:102)
    at t.refreshViewItem (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:444:754)
    at t.onInsertItem (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:444:419)
    at t.e.onInsertItems (file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:324:677)
```

**Comment by jreina** [comment]
I think this is a rendering issue caused by VS Code Microsoft/vscode#45549

Looks like a fix is in place. I will keep an eye on [this milestone](https://github.com/Microsoft/vscode/milestone/64) and hope that takes care of it.

**Comment by maty21** [comment]
Tks man that really helpful which vscode version you using

**Comment by jreina** [comment]
From my "about" screen:
```
Version 1.21.0
Commit 9a199d77c82fcb82f39c68bb33c614af01c111ba
Date 2018-03-07T11:04:09.969Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

**Comment by maty21** [comment]
Thanks :)

**Comment by jreina** [comment]
No problem. I built VS Code from master and the issue was resolved in [this commit](https://github.com/Microsoft/vscode/commit/5478bd938ef9c871b43f776074f19b275baf1c62). Now we wait for the next VS Code release!

**Comment by jreina** [comment]
The issue was fixed in the March 2018 release of VS Code.
